package net.projecteuler.euler;
/**
 * Created by Tigrenok on 04.06.2017.
 */

/** Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

public class Task_02 {
    public static void main(String[] args){
        int sum = 2; //объявляем сумму - она состоит из (n2 = 2) - то есть только первый член
        int x = 0; //очередной член последовательности
        int n1 = 1, n2 = 2; //это два предыдущих члена

        while (x < 4000000)
        {
            x = n1 + n2; //определяем следующий член прогрессии
            n1 = n2; //для следующего члена присваиваем новые значения - двигаемся как бы вправо по последовательности
            n2 = x;
            if (x%2==0) sum += x; //суммируем только четные члены
        }
        System.out.println(sum);
    }
}
